[package]
name = "bauth_server"
authors.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bauth_core = { path = "../bauth_core" }
axum.workspace = true
tokio.workspace = true
dotenvy.workspace = true
tower-http.workspace = true
envconfig.workspace = true
sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
argon2.workspace = true
thiserror.workspace = true
governor.workspace = true
tokio-cron-scheduler.workspace = true
arc-swap.workspace = true
utoipa.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
getrandom.workspace = true
sha2.workspace = true
base64.workspace = true
lettre.workspace = true
toml.workspace = true
url.workspace = true
chacha20poly1305.workspace = true
aws-lc-rs.workspace = true
jsonwebtoken.workspace = true

[dev-dependencies]
tower = { version = "~0.5", features = ["util"] }
